### ISSUE TITLE
[sysdig-deploy] Duplicated k8s_coldstart settings

### ISSUE THREAD

**Issue by irozzo-1A** [sysdiglabs/charts#1068]
When installing `sysdig/sysdig-deploy` chart with the cold-start values e.g.

```
  sysdig:
    settings:
      k8s_coldstart:
        max_parallel_cold_start: 0
```

The generated agent config map contains a duplicated empty value i.e.

```
apiVersion: v1
data:
  dragent.yaml: |
    new_k8s: true
    k8s_cluster_name: esc-3113
    collector: collector-staging.sysdigcloud.com
    collector_port: 6443
    security:
      enabled: true
      k8s_audit_server_enabled: true
      k8s_audit_server_port: 7765
      k8s_audit_server_url: 0.0.0.0
    k8s_coldstart: {}


    k8s_coldstart:
      max_parallel_cold_start: 0
```
