### ISSUE TITLE
sysdig-agent daemonset does not respects rolling update strategy

### ISSUE THREAD

**Issue by vipulagarwal** [sysdiglabs/charts#1655]
I have observed that sysdig-agent daemonset ignores the rolling update strategy and it takes around 10 minutes to pass readiness checks.

Upon upgrading the helm chart, all the agent pods are replaced with new pods in spite of the readiness check failing on the newly created pods.
```
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

However, node-analyzer with the same  `updateStrategy` works as expected.

I understand this could be unrelated to the helm charts and please feel free to point me in the right direction. Thank you!

**Comment by aroberts87** [comment]
Hi @vipulagarwal! Thanks for raising an issue. Can you please confirm that your `updateStrategy` blocks are located at the expected locations? As an example:

```yaml
agent:
  daemonset:
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
nodeAnalyzer:
  daemonset:
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
```

**Comment by vipulagarwal** [comment]
Yes, the `updateStrategy` blocks are in the right place. I have observed that moving to the `universal_ebpf` driver has solved the problem. I am still not sure why `updateStrategy` is not respected when using the `legacy_ebpf` driver.

**Comment by AlbertoBarba** [comment]
@vipulagarwal we did investigate this issue and, from our findings, it seems caused by an update on the configmap.
What's happening is that, during the rollout of a new version, old pods will recognise that the configuration has changed and will proceed to restart all the affected internal process. During this restart, the readiness probe will return an error and, after ~9 secs, k8s will mark the pod as not ready. The RollingUpdate strategy seems to pick also all the "not ready" pods as candidate for the new release.
As a quick and temporary file i can suggest u to increase the readiness probe periodSeconds like:
```yaml
  daemonset:
    probes:
      periodDelay: 10
```
This should allow the agent to recover from a config update and will not cause issues during a rolling update.
Meanwhile we are working on fixing it with more robust default configurations
