### ISSUE TITLE
install fails with error on newer helm versions

### ISSUE THREAD

**Issue by pschulten** [sysdiglabs/charts#2227]
I get an error on helm install:
```
coalesce.go:298: warning: cannot overwrite table with non table for sysdig-deploy.agent.daemonset (map[affinity:map[] annotations:map[] arch:[amd64 arm64 s390x] deploy:true env:map[] kmodule:map[env:map[] extraVolumes:map[mounts:[] volumes:[]]] labels:map[] nodeSelector:map[] os:[linux] probes:map[failureThreshold:9 initialDelay:90 periodDelay:10] updateStrategy:map[rollingUpdate:map[] type:RollingUpdate]])
Error: UPGRADE FAILED: template: sysdig-deploy/charts/agent/templates/daemonset.yaml:1:17: executing "sysdig-deploy/charts/agent/templates/daemonset.yaml" at <.Values.daemonset.deploy>: nil pointer evaluating interface {}.deploy
```

this is how I install:
```shell
export SYSDIG_VERSION=1.80.1
helm repo add sysdig https://charts.sysdig.com/
helm repo update
helm upgrade --install --version $SYSDIG_VERSION sysdig sysdig/sysdig-deploy --values sysdig.yaml --create-namespace --namespace sysdig
```

<details>

<summary>this is my values file (`sysdig.yaml`):</summary>

```yaml
  global:
    sysdig:
      accessKey: SOME_KEY
      region: SOME_REGION
      tags:
        key1: value1
        key2: value2
    clusterConfig:
      name: SOME_NAME
    kspm:
      deploy: true

  kspmCollector:
    enabled: false

  admissionController:
    enabled: false

  nodeAnalyzer:
    nodeAnalyzer:
      tolerations:
        - operator: Exists
      benchmarkRunner:
        deploy: false
      runtimeScanner:
        deploy: true
      hostScanner:
        scanOnStart: true
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            memory: 150Mi
      kspmAnalyzer:
        resources:
          requests:
            cpu: 150m
            memory: 512Mi
          limits:
            memory: 512Mi
    secure:
      vulnerabilityManagement:
        newEngineOnly: true

  agent:
    tolerations:
      - operator: Exists
    daemonset:
    monitor:
      enabled: false
    ebpf:
      enabled: true
      kind: universal_ebpf
    privileged: false
    sysdig:
      settings:
        feature:
          mode: secure # or secure_light
    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 250m
        memory: 1000Mi

  clusterShield:
    tolerations:
      - operator: Exists
    enabled: true
    cluster_shield:
      features:
        admission_control:
          enabled: false
        audit:
          enabled: true
        container_vulnerability_management:
          enabled: true
        posture:
          enabled: true
        kubernetes_metadata:
          enabled: true

```

</details>

This happened after I updated my helm version to the (current) latest: `v3.17.3`

I then downgraded the version and the first version that worked again was `v3.17.0`

Is there something wrong with my values file or is this a bug?

**Comment by francesco-furlan** [comment]
Hi @pschulten,
we saw that from `Helm v3.17.1` [this](https://github.com/helm/helm/pull/12879) has been fixed. So each `null` value will now override the default of the subcharts.

In your cases:
```
  agent:
    tolerations:
      - operator: Exists
    daemonset: <--- here the issue
```

Since `daemonset` is empty it will now be passed to the agent subchart and cause the issue you encountered.

Let us know if removing the `daemonset` key fixes the issue
